res: 128

model:
  base_learning_rate: 1.0e-4
  target: vae.models.autoencoder.VQModel
  params:
    # ckpt_path: null
    monitor: train/nll_loss
    embed_dim: 4
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: ${res}
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: vae.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_start: 100_000_000
        disc_num_layers: 3
        codebook_weight: 1.0
        disc_weight: 0.75
        n_classes: ${model.params.n_embed}
        clip_weight: 1.0 
    optim_config:
      lr_g_factor: 1
      scheduler_config:
        target: vae.lr_scheduler.LambdaLinearScheduler
        params:
          verbosity_interval: 0
          warm_up_steps: [2000]
          f_min: [1]
          f_max: [1]
          f_start: [0]
          cycle_lengths: [100_000_000]
    clip_feat_key: clip_feat
    clip_cfg:
      clip_feature_dim: 512 # z_channels will be projected to it  
      in_res: 16 # from resolution and ch_mult
      f_res: 8 # self-attn resolution
      heads: 8 # dim of encoder output // heads == dim per channel in self-attn ; make sure it's 64

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 4
    train:
      target: vae.data.custom.CustomTrain
      params:
        training_images_list_file: data/coco2014/custom_train.txt
        size: ${res}
        with_clip_feat: true
    validation:
      target: vae.data.custom.CustomTest
      params:
        test_images_list_file: data/coco2014/custom_val.txt
        size: ${res}
        with_clip_feat: true

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 16
        increase_log_steps: false
  trainer:
    max_epochs: 10
    check_val_every_n_epoch: 2
    # log_every_n_steps: 10
    precision: 16
    benchmark: true
    accumulate_grad_batches: 1